/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with username and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example student_ali */
                        username: string;
                        /** @example password123 */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Login successful */
                            message?: string;
                            data?: {
                                user?: {
                                    /** Format: uuid */
                                    id?: string;
                                    username?: string;
                                    /** Format: email */
                                    email?: string;
                                    displayName?: string;
                                    /** @enum {string} */
                                    role?: "STUDENT" | "TUTOR" | "ADMIN";
                                    avatarUrl?: string | null;
                                    isActive?: boolean;
                                    subscription?: {
                                        /** @enum {string} */
                                        plan?: "FREE" | "PREMIUM";
                                        /** @enum {string} */
                                        status?: "ACTIVE" | "INACTIVE" | "CANCELLED" | "PAST_DUE";
                                    } | null;
                                };
                                /** @description JWT access token (expires in 15 minutes) */
                                accessToken?: string;
                                /** @description JWT refresh token (expires in 7 days) — store securely */
                                refreshToken?: string;
                            };
                        };
                    };
                };
                /** @description Invalid username or password */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Invalid username or password */
                            message?: string;
                            /** @example null */
                            data?: unknown;
                        };
                    };
                };
                /** @description Account deactivated */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error (missing fields) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Obtain a new access token using a valid refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The refresh token received at login */
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description New access token issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Access token refreshed */
                            message?: string;
                            data?: {
                                accessToken?: string;
                            };
                        };
                    };
                };
                /** @description Invalid or expired refresh token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and invalidate the refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The refresh token to revoke */
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description Logged out successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Logged out successfully */
                            message?: string;
                            /** @example null */
                            data?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all classes (paginated) — Admin only */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Number of classes per page */
                    limit?: number;
                    /** @description Filter by class status */
                    status?: "ACTIVE" | "INACTIVE";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of classes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Classes retrieved successfully */
                            message?: string;
                            data?: {
                                /** Format: uuid */
                                id?: string;
                                className?: string;
                                classCode?: string;
                                classCategory?: string | null;
                                /** @enum {string} */
                                classStatus?: "ACTIVE" | "INACTIVE";
                                /** Format: date-time */
                                createdAt?: string;
                                /** @description Total number of enrolled users */
                                memberCount?: number;
                            }[];
                            meta?: {
                                page?: number;
                                limit?: number;
                                total?: number;
                                totalPages?: number;
                            };
                        };
                    };
                };
                /** @description Invalid query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authenticated but not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single class by ID (with enrolled members) — Admin only */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Class UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Class detail with enrolled members */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Class retrieved successfully */
                            message?: string;
                            data?: {
                                /** Format: uuid */
                                id?: string;
                                className?: string;
                                classCode?: string;
                                classCategory?: string | null;
                                /** @enum {string} */
                                classStatus?: "ACTIVE" | "INACTIVE";
                                /** Format: date-time */
                                createdAt?: string;
                                /** Format: date-time */
                                updatedAt?: string;
                                members?: {
                                    /**
                                     * Format: uuid
                                     * @description ClassUser join record ID
                                     */
                                    id?: string;
                                    /**
                                     * @description Role of the user within this class
                                     * @enum {string}
                                     */
                                    role?: "STUDENT" | "TUTOR" | "ADMIN";
                                    user?: {
                                        /** Format: uuid */
                                        id?: string;
                                        username?: string;
                                        displayName?: string;
                                        avatarUrl?: string | null;
                                    };
                                }[];
                            };
                        };
                    };
                };
                /** @description Invalid UUID format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authenticated but not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Class not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users (paginated) — Admin only */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Number of users per page */
                    limit?: number;
                    /** @description Filter by role */
                    role?: "STUDENT" | "TUTOR" | "ADMIN";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of users */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Users retrieved successfully */
                            message?: string;
                            data?: {
                                /** Format: uuid */
                                id?: string;
                                username?: string;
                                email?: string;
                                displayName?: string;
                                avatarUrl?: string | null;
                                isActive?: boolean;
                                /** @enum {string} */
                                role?: "STUDENT" | "TUTOR" | "ADMIN";
                                phoneNumber?: string | null;
                                /** Format: date-time */
                                createdAt?: string;
                            }[];
                            meta?: {
                                page?: number;
                                limit?: number;
                                total?: number;
                                totalPages?: number;
                            };
                        };
                    };
                };
                /** @description Invalid query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authenticated but not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single user by ID (full profile) — Admin only */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Full user profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example User retrieved successfully */
                            message?: string;
                            data?: {
                                /** Format: uuid */
                                id?: string;
                                username?: string;
                                email?: string;
                                displayName?: string;
                                avatarUrl?: string | null;
                                isActive?: boolean;
                                /** @enum {string} */
                                role?: "STUDENT" | "TUTOR" | "ADMIN";
                                phoneNumber?: string | null;
                                /** Format: date-time */
                                createdAt?: string;
                                /** Format: date-time */
                                updatedAt?: string;
                                learnerProfile?: {
                                    /** Format: uuid */
                                    id?: string;
                                    currentLevel?: string | null;
                                    targetLevel?: string | null;
                                    learningPurpose?: string | null;
                                    weeklyGoalMinutes?: number;
                                    timezone?: string;
                                    uiLanguage?: string;
                                    theme?: string;
                                } | null;
                                subscription?: {
                                    /** Format: uuid */
                                    id?: string;
                                    /** @enum {string} */
                                    plan?: "FREE" | "PREMIUM";
                                    /** @enum {string} */
                                    status?: "ACTIVE" | "INACTIVE" | "CANCELLED" | "PAST_DUE";
                                    /** Format: date-time */
                                    currentPeriodStart?: string | null;
                                    /** Format: date-time */
                                    currentPeriodEnd?: string | null;
                                } | null;
                                metrics?: {
                                    /** Format: uuid */
                                    id?: string;
                                    totalStudyTimeMinutes?: number;
                                    totalWordsTyped?: number;
                                    lessonsCompleted?: number;
                                    currentStreak?: number;
                                    longestStreak?: number;
                                    /** Format: date-time */
                                    lastStudyDate?: string | null;
                                    estimatedLevel?: string | null;
                                } | null;
                                classUsers?: {
                                    /** Format: uuid */
                                    id?: string;
                                    /** @enum {string} */
                                    role?: "STUDENT" | "TUTOR" | "ADMIN";
                                    class?: {
                                        /** Format: uuid */
                                        id?: string;
                                        className?: string;
                                        classCode?: string;
                                        /** @enum {string} */
                                        classStatus?: "ACTIVE" | "INACTIVE";
                                    };
                                }[];
                            };
                        };
                    };
                };
                /** @description Invalid UUID format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authenticated but not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example false */
            success?: boolean;
            message?: string;
            /** @example null */
            data?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
