/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new account with email and password
         * @description Creates a new user account. On success, returns tokens immediately so the user is logged in right away — no separate login step required.
         *     **Default state after registration:** - `subscription.plan` = FREE - `subscription.status` = INACTIVE - AI chatbot access is **disabled** until the user subscribes (Phase 8) - Class joining via class code works immediately (no subscription needed)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Unique. Letters, numbers, and underscores only.
                         * @example student_ali
                         */
                        username: string;
                        /**
                         * Format: email
                         * @example ali@example.com
                         */
                        email: string;
                        /** @example MyPassword123 */
                        password: string;
                        /** @example Ali Hassan */
                        displayName: string;
                    };
                };
            };
            responses: {
                /** @description Registration successful — user is logged in */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Registration successful */
                            message?: string;
                            data?: components["schemas"]["AuthResponse"];
                        };
                    };
                };
                /** @description Username or email already registered */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Validation error (missing or invalid fields) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login with username and password
         * @description Standard email/password login. Returns an access token (15m) and a refresh token (7d). If the account was created with Google Sign-In (no password), a 401 is returned with a clear message directing the user to Google login.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example student_ali */
                        username: string;
                        /** @example password123 */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Login successful */
                            message?: string;
                            data?: components["schemas"]["AuthResponse"];
                        };
                    };
                };
                /** @description Invalid credentials, or account uses Google Sign-In */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Account deactivated */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Validation error (missing fields) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in or register with Google
         * @description Verifies a Google ID token (obtained from Google Sign-In on the frontend) and handles all three cases automatically:
         *     **Case 1 — Existing Google user:** logs them in, returns tokens.
         *     **Case 2 — Account merge:** if a user already has an email/password account with the same email, their Google account is linked automatically and tokens are returned. They can now sign in with either method.
         *     **Case 3 — New user (needs username):** if no account exists, returns `{ needsRegistration: true, profile: { email, displayName, avatarUrl } }`. The frontend should show a username input, then call this endpoint again with both `idToken` and `username`.
         *     **Case 4 — New user (username provided):** creates the account and returns tokens.
         *     **How to get an ID token on the frontend:** Use Google's [Sign In With Google](https://developers.google.com/identity/gsi/web/guides/overview) button or the `@react-oauth/google` / `vue3-google-login` library. The `credential` field from the Google callback is the `idToken` to send here.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Google ID token (JWT) from the frontend Google Sign-In flow
                         * @example eyJhbGciOiJSUzI1NiIsImtpZCI6...
                         */
                        idToken: string;
                        /**
                         * @description Required only for new users (when needsRegistration was true)
                         * @example john_doe
                         */
                        username?: string;
                    };
                };
            };
            responses: {
                /** @description Authentication successful — OR — username required (needsRegistration: true). Check the `data.needsRegistration` field to distinguish. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            message?: string;
                            data?: {
                                /** @example false */
                                needsRegistration?: boolean;
                                user?: components["schemas"]["AuthUser"];
                                accessToken?: string;
                                refreshToken?: string;
                            } | {
                                /** @example true */
                                needsRegistration?: boolean;
                                profile?: {
                                    googleId?: string;
                                    /** Format: email */
                                    email?: string;
                                    displayName?: string;
                                    avatarUrl?: string | null;
                                };
                            };
                        };
                    };
                };
                /** @description Invalid or expired Google ID token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Username already taken */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Google OAuth is not configured on this server (missing GOOGLE_CLIENT_ID) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Obtain a new access token using a valid refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The refresh token received at login or registration */
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description New access token issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Access token refreshed */
                            message?: string;
                            data?: {
                                accessToken?: string;
                            };
                        };
                    };
                };
                /** @description Invalid or expired refresh token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and invalidate the refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The refresh token to revoke */
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description Logged out successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Logged out successfully */
                            message?: string;
                            /** @example null */
                            data?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all classes (paginated) — Admin only */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    status?: "ACTIVE" | "INACTIVE";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of classes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Classes retrieved successfully */
                            message?: string;
                            data?: {
                                /** Format: uuid */
                                id?: string;
                                className?: string;
                                classCode?: string;
                                classCategory?: string | null;
                                /** @enum {string} */
                                classStatus?: "ACTIVE" | "INACTIVE";
                                classCodeBlocked?: boolean;
                                /** Format: date-time */
                                classCodeExpiresAt?: string | null;
                                classCodeRefreshIntervalSeconds?: number | null;
                                /** Format: date-time */
                                createdAt?: string;
                                memberCount?: number;
                            }[];
                            meta?: {
                                page?: number;
                                limit?: number;
                                total?: number;
                                totalPages?: number;
                            };
                        };
                    };
                };
                /** @description Invalid query */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a new class (Tutor or Admin)
         * @description Creates a class and adds the caller to it as a TUTOR member.
         *     A fresh class code is generated immediately.
         *
         *     If `classCodeRefreshIntervalSeconds` is omitted or null, the code is
         *     permanent (no automatic expiry). The tutor can still rotate it manually.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        className: string;
                        classCategory?: string | null;
                        /**
                         * @description Auto-refresh interval in seconds. Common presets:
                         *     86400 (daily), 604800 (weekly), 2592000 (monthly),
                         *     31536000 (yearly). Omit or null = no auto refresh.
                         */
                        classCodeRefreshIntervalSeconds?: number | null;
                    };
                };
            };
            responses: {
                /** @description Class created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not a tutor or admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join a class by entering its code
         * @description Joins the caller to the class identified by the supplied code.
         *     No tutor approval is required.
         *
         *     Codes are case-insensitive and trimmed before matching.
         *
         *     Possible failure reasons:
         *     - **404** — code does not match any class
         *     - **403** — code is currently blocked by the tutor
         *     - **409** — class is INACTIVE, or caller is already a member
         *     - **410** — code has expired (the system will have rotated it
         *       to a new value internally; ask the tutor for the new code)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example XK7A9PQ2 */
                        classCode: string;
                    };
                };
            };
            responses: {
                /** @description Successfully joined the class */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            message?: string;
                            data?: {
                                /** Format: uuid */
                                classId?: string;
                                className?: string;
                                classCode?: string;
                                /** @enum {string} */
                                role?: "STUDENT" | "TUTOR" | "ADMIN";
                                /** Format: date-time */
                                joinedAt?: string;
                            };
                        };
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Code is blocked */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Code does not match a class */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Already a member or class inactive */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Code has expired */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the classes the authenticated user is a member of */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Caller's class memberships */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single class by ID with members — Admin only */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Class detail with enrolled members */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid UUID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Class not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/{id}/code/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manually rotate the class code (Tutor in class or Admin)
         * @description Generates a new random code and resets the expiry window using
         *     the class's current refresh interval. Does not unblock a blocked code.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description New code information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            message?: string;
                            data?: components["schemas"]["ClassCodeInfo"];
                        };
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not a tutor of this class */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Class not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/{id}/code/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the class code auto-refresh interval (Tutor in class or Admin)
         * @description Sets how often the class code auto-refreshes. The new schedule
         *     takes effect immediately, computed from the last refresh timestamp.
         *
         *     Pass `null` to make the code permanent (no automatic refresh).
         *
         *     Common presets (in seconds):
         *     - daily: 86400
         *     - weekly: 604800
         *     - monthly: 2592000
         *     - yearly: 31536000
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        classCodeRefreshIntervalSeconds: number | null;
                    };
                };
            };
            responses: {
                /** @description Updated code information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            message?: string;
                            data?: components["schemas"]["ClassCodeInfo"];
                        };
                    };
                };
                /** @description Invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not a tutor of this class */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Class not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/classes/{id}/code/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Block or unblock the class code (Tutor in class or Admin)
         * @description Blocking does not change the code value or its expiry — it only
         *     prevents new join attempts. Pass `{ blocked: false }` to unblock.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        blocked: boolean;
                    };
                };
            };
            responses: {
                /** @description Updated code information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            message?: string;
                            data?: components["schemas"]["ClassCodeInfo"];
                        };
                    };
                };
                /** @description Invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not a tutor of this class */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Class not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users (paginated) — Admin only */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Number of users per page */
                    limit?: number;
                    /** @description Filter by role */
                    role?: "STUDENT" | "TUTOR" | "ADMIN";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of users */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Users retrieved successfully */
                            message?: string;
                            data?: {
                                /** Format: uuid */
                                id?: string;
                                username?: string;
                                email?: string;
                                displayName?: string;
                                avatarUrl?: string | null;
                                isActive?: boolean;
                                /** @enum {string} */
                                role?: "STUDENT" | "TUTOR" | "ADMIN";
                                phoneNumber?: string | null;
                                /** Format: date-time */
                                createdAt?: string;
                            }[];
                            meta?: {
                                page?: number;
                                limit?: number;
                                total?: number;
                                totalPages?: number;
                            };
                        };
                    };
                };
                /** @description Invalid query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authenticated but not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single user by ID (full profile) — Admin only */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Full user profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example User retrieved successfully */
                            message?: string;
                            data?: {
                                /** Format: uuid */
                                id?: string;
                                username?: string;
                                email?: string;
                                displayName?: string;
                                avatarUrl?: string | null;
                                isActive?: boolean;
                                /** @enum {string} */
                                role?: "STUDENT" | "TUTOR" | "ADMIN";
                                phoneNumber?: string | null;
                                /** Format: date-time */
                                createdAt?: string;
                                /** Format: date-time */
                                updatedAt?: string;
                                learnerProfile?: {
                                    /** Format: uuid */
                                    id?: string;
                                    currentLevel?: string | null;
                                    targetLevel?: string | null;
                                    learningPurpose?: string | null;
                                    weeklyGoalMinutes?: number;
                                    timezone?: string;
                                    uiLanguage?: string;
                                    theme?: string;
                                } | null;
                                subscription?: {
                                    /** Format: uuid */
                                    id?: string;
                                    /** @enum {string} */
                                    plan?: "FREE" | "PREMIUM";
                                    /** @enum {string} */
                                    status?: "ACTIVE" | "INACTIVE" | "CANCELLED" | "PAST_DUE";
                                    /** Format: date-time */
                                    currentPeriodStart?: string | null;
                                    /** Format: date-time */
                                    currentPeriodEnd?: string | null;
                                } | null;
                                metrics?: {
                                    /** Format: uuid */
                                    id?: string;
                                    totalStudyTimeMinutes?: number;
                                    totalWordsTyped?: number;
                                    lessonsCompleted?: number;
                                    currentStreak?: number;
                                    longestStreak?: number;
                                    /** Format: date-time */
                                    lastStudyDate?: string | null;
                                    estimatedLevel?: string | null;
                                } | null;
                                classUsers?: {
                                    /** Format: uuid */
                                    id?: string;
                                    /** @enum {string} */
                                    role?: "STUDENT" | "TUTOR" | "ADMIN";
                                    class?: {
                                        /** Format: uuid */
                                        id?: string;
                                        className?: string;
                                        classCode?: string;
                                        /** @enum {string} */
                                        classStatus?: "ACTIVE" | "INACTIVE";
                                    };
                                }[];
                            };
                        };
                    };
                };
                /** @description Invalid UUID format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authenticated but not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example false */
            success?: boolean;
            message?: string;
            /** @example null */
            data?: unknown;
        };
        AuthUser: {
            /** Format: uuid */
            id?: string;
            username?: string;
            /** Format: email */
            email?: string;
            displayName?: string;
            /** @enum {string} */
            role?: "STUDENT" | "TUTOR" | "ADMIN";
            avatarUrl?: string | null;
            isActive?: boolean;
            /** @description FREE + INACTIVE = no AI access (default after registration). PREMIUM + ACTIVE = full AI chatbot access. */
            subscription?: {
                /** @enum {string} */
                plan?: "FREE" | "PREMIUM";
                /** @enum {string} */
                status?: "ACTIVE" | "INACTIVE" | "CANCELLED" | "PAST_DUE";
            } | null;
        };
        AuthTokens: {
            /** @description JWT access token — expires in 15 minutes. Send as Bearer token in Authorization header. */
            accessToken?: string;
            /** @description JWT refresh token — expires in 7 days. Store securely (httpOnly cookie or secure storage). */
            refreshToken?: string;
        };
        AuthResponse: {
            user?: components["schemas"]["AuthUser"];
            accessToken?: string;
            refreshToken?: string;
        };
        ClassCodeInfo: {
            /** Format: uuid */
            classId?: string;
            classCode?: string;
            classCodeBlocked?: boolean;
            /**
             * Format: date-time
             * @description Null means the code never expires automatically
             */
            classCodeExpiresAt?: string | null;
            /** @description Auto-refresh interval in seconds. Null means no auto refresh. */
            classCodeRefreshIntervalSeconds?: number | null;
            /** Format: date-time */
            classCodeRefreshedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
