'use strict';
const express = require('express');
const router = express.Router();
const ctrl = require('./goals.controller');
const { requireJwtAuth } = require('../../../middleware/auth.middleware');
router.get('/',    requireJwtAuth, ctrl.list);
router.post('/',   requireJwtAuth, ctrl.create);
router.put('/:id', requireJwtAuth, ctrl.update);
router.delete('/:id', requireJwtAuth, ctrl.remove);
module.exports = router;
