'use strict';
const express = require('express');
const router = express.Router();
const ctrl = require('./vocabulary.controller');
const { requireJwtAuth } = require('../../../middleware/auth.middleware');
router.get('/',              requireJwtAuth, ctrl.list);
router.post('/',             requireJwtAuth, ctrl.add);
router.put('/:id',           requireJwtAuth, ctrl.update);
router.delete('/:id',        requireJwtAuth, ctrl.remove);
router.get('/due',           requireJwtAuth, ctrl.getDueCards);
router.post('/:id/practice', requireJwtAuth, ctrl.recordPractice);
module.exports = router;
